create table if not exists reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  anime_id bigint references animes(id) on delete cascade not null,
  rating decimal(3,1) check (rating >= 0 and rating <= 10),
  content text not null,
  is_spoiler boolean default false,
  is_verified_critic boolean default false,
  helpful_count int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
  unique(user_id, anime_id)
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  anime_id bigint references animes(id) on delete cascade not null,
  episode_id bigint references episodes(id) on delete cascade,
  parent_id bigint references comments(id) on delete cascade,
  content text not null,
  is_spoiler boolean default false,
  is_pinned boolean default false,
  like_count int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table reviews enable row level security;
alter table comments enable row level security;

create policy "Reviews are viewable by everyone" on reviews for select using (true);
create policy "Users can insert their own reviews" on reviews for insert with check (auth.uid() = user_id);
create policy "Users can update their own reviews" on reviews for update using (auth.uid() = user_id);
create policy "Users can delete their own reviews" on reviews for delete using (auth.uid() = user_id);

create policy "Comments are viewable by everyone" on comments for select using (true);
create policy "Users can insert their own comments" on comments for insert with check (auth.uid() = user_id);
create policy "Users can update their own comments" on comments for update using (auth.uid() = user_id);
create policy "Users can delete their own comments" on comments for delete using (auth.uid() = user_id);

-- Admin moderation policies
create policy "Admins can delete any comment" on comments for delete using (
    exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);

create policy "Admins can delete any review" on reviews for delete using (
    exists (
        select 1 from profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);
